server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:postgresql://localhost:5432/4wheels_drive_db
    username: cosminacho
    password: cosminacho

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/liquibase-changelog.yml

  mail:
    host: smtp.gmail.com
    port: 587
    username: bot.4wheelsdrive@gmail.com
    password: mzudojeuuaxlhpzk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  authentication:
    key: 397A24432646294A404E635266556A586E327235753878214125442A472D4B61
    token:
#      duration: 3600000
       duration: 300000

registration_service:
  token_active_time: PT15M
