package com.upb.fourwheelsdrive.utils;

public final class Constants {
    public final static String USERNAME_NOT_FOUND = "Username not found.";
    public final static String USERNAME_ALREADY_REGISTERED = "Username already registered.";
    public final static String INVALID_REGISTRATION_TOKEN = "Invalid registration token.";
    public final static String REGISTRATION_TOKEN_EXPIRED = "Registration token expired.";
    public final static String ACCOUNT_ALREADY_ACTIVATED = "The account has already been activated.";
    public final static String ACCOUNT_ACTIVATED = "The account has been activated.";
    public final static String ACCOUNT_NOT_ACTIVATED = "The account is not activated.";
    public final static String ACCOUNT_LOCKED = "The account is locked.";
    public final static String BAD_CREDENTIALS = "Username or password are incorrect.";
    public final static String INVALID_AUTHENTICATION_TOKEN = "Invalid or expired token.";
    public final static String PARSE_JSON_ERROR = "Error at parsing JSON";
    public final static String ROLE_ADMIN = "ROLE_ADMIN";
    public final static String ROLE_USER = "ROLE_USER";
    public final static String UNAUTHORIZED_ACCESS = "Unauthorized access.";
    public final static String RESET_PASSWORD_EMAIL_SENT = "An email for resetting your password has been sent.";
    public final static String PASSWORD_RESET_SUCCESSFULLY = "Password has been reset. Now you can log in.";
    public final static String BAD_REQUEST = "Bad request";
    public final static String ACCOUNT_CREATED = "The account has been created. An e-mail has been sent with the activation link.";
    public final static String ACTIVATION_LINK_RESENT = "An e-mail has been send with the activation link.";
    public final static String AUTHENTICATION_SUCCESSFUL = "The authentication has been successful.";
    public final static String CAR_MISSING_INFO = "Information about car is missing.";
    public final static String CAR_ADVERT_CREATED = "The advertisement has been successfully created!";
    public final static String INVALID_CAR_MODEL = "The car model does not exist in the database.";
    public final static String INVALID_CAR_MODEL_GENERATION = "The car model generation does not exist in the database.";
    public final static String INVALID_CAR_BRAND = "The car brand does not exist in the database.";
    public final static String CAR_ADVERT_EDITED = "The advertisement has been successfully edited!";
    public final static String CAR_ADVERT_MISSING = "The requested car advert is missing...";
    public final static String CAR_ADVERT_DELETED = "The advertisement has been successfully deleted!";
    public final static String OOPS = "OOPS, bad request... :(";
    public final static String BRAND_ADDED = "A new vehicle brand has been added!";
    public final static String MODEL_ADDED = "A new brand model has been added!";
    public final static String GENERATION_ADDED = "A new model generation has been added!";
    public final static String BRAND_ALREADY_EXISTS = "The vehicle brand already exists in the database!";
    public final static String MODEL_ALREADY_EXISTS = "The brand model already exists in the database!";
    public final static String GENERATION_ALREADY_EXISTS = "The model generation already exists in the database!";
    public final static String ADVERT_ADDED_FAVORITE = "The advert has been added to favorite list.";
    public final static String AD_ALREADY_MARKED_AS_FAVORITE = "The advert has already been marked as favorite.";
    public final static String AD_NOT_MARKED_AS_FAVORITE = "The advert was not marked as favorite.";
    public final static String INVALID_FILTER_PARAMS = "Invalid filter parameters.";
}
